-- Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
--
-- 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
--
-- It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
--
-- Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?


module P044 where

import Helpers

pentagonal n = n * (3 * n - 1) / 2

isPentagonal n = (forumla) == (fromIntegral $ floor forumla)
    where
    forumla = (1 + (sqrt (1 + (24 * n)))) / 6

pentagonalList = map (pentagonal) [1..]

brute = head [(j,k,j-k) | j <- pentagonalList, k <- pentagonalList, j > k, isPentagonal (j + k), isPentagonal (j - k) ]

solution (j:js) [] = solution (js) (reverse $ takeWhile (<=j) pentagonalList)
solution (j:js) (k:ks)
    | isPentagonal (j + k) && isPentagonal (j - k) = (j,k,j-k)
    | otherwise = solution (j:js) (ks)